server:
 port: 8089
 
spring:
 h2:
  console:
   enabled: true
 datasource:
  username: root
  password: root
  url: jdbc:mysql://127.0.0.1:6033/FlorenceOn
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  properties:
   hibernate: 
    dialect: org.hibernate.dialect.MySQL5Dialect
    ddl-auto: update
  show-sql: true

#OpenAPI
springdoc:
  packagesToScan: com.ithakasoftware.florenceon
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
    url: /v3/api-docs